title: National Parks  Rail Corridor (Central)
url: ""
favicon: /images/favicon-isomer.ico
colors:
  primary-color: "#7f674e"
  secondary-color: "#7f674e"
  media-colors:
    - title: media-color-one
      color: "#f99b0c"
    - title: media-color-two
      color: "#7f7e7c"
    - title: media-color-three
      color: "#d6b567"
    - title: media-color-four
      color: "#7a9a01"
    - title: media-color-five
      color: "#00838f"
resources_name: Resource
description: An Isomer site of the Singapore Government
permalink: none
baseurl: ""
exclude:
  - travis-script.js
  - .travis.yml
  - README.md
  - package.json
  - package-lock.json
  - node_modules
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/
  - Gemfile
  - Gemfile.lock
include:
  - _redirects
defaults:
  - scope:
      path: ""
    values:
      layout: page
custom_css_path: /misc/custom.css
custom_print_css_path: /assets/css/print.css
paginate: 12
remote_theme: isomerpages/isomerpages-template@next-gen
safe: false
plugins:
  - jekyll-feed
  - jekyll-assets
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-remote-theme
staging: https://nparks-test1-staging.netlify.app
prod: https://nparks-test1-prod.netlify.app
is_government: true
